version: 3

tasks:
  install:
    cmds:
    # - rm -rf ~/.task
    # - mkdir -p ~/.task
    # - cp -R . ~/.task
    - cp TaskfileGlobal.yaml ~/Taskfile.yaml

  release:
    vars:
      VERSION: 
        sh: yq '.vars.VERSION' TaskfileGlobal.yaml 
    cmds:
    - git tag {{ .VERSION }}
    - git push origin {{ .VERSION }}