version: 3

includes:
  ec2: 
    taskfile: ec2/Taskfile.yaml
  ssm:
    taskfile: ssm/Taskfile.yaml
  lb:
    taskfile: lb/Taskfile.yaml
  vpc:
    taskfile: vpc/Taskfile.yaml
  eks:
    taskfile: eks/Taskfile.yaml