version: 3

tasks:
  api:list:rulesets:
    vars:
      API_TOKEN: 
        sh: echo $CLOUDFLARE_API_KEY 
      ZONE_ID: '{{ .ZONE_ID }}'
    requires:
      vars:
      - ZONE_ID
    cmds:
    - silent: false
      cmd: >
        curl https://api.cloudflare.com/client/v4/zones/{{ .ZONE_ID }}/rulesets
        --header "Authorization: Bearer {{ .API_TOKEN }}"
    preconditions:
      - sh: test ! -z "$CLOUDFLARE_API_KEY"
        msg: "CLOUDFLARE_API_KEY is not set"