version: 3

tasks:
  install:
    desc: |
      Install Go in {{ .VERSION }} version.
    vars:
      VERSION: 1.21.5
    cmds:
    - wget -nc https://go.dev/dl/go{{ .VERSION }}.{{ OS }}-{{ ARCH }}.tar.gz -O go.tar.gz
    - defer: rm go.tar.gz
    - sudo rm -rf /usr/local/go
    - sudo tar -C /usr/local -xzf go.tar.gz
    - /usr/local/go/bin/go version
    - cowsay "Remember to reload shell"
    status:
    - go version | grep {{ .VERSION }}